# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b55c510594cdb04ee4809b8fa43555b4d294b63e6eb299b23b427dae7e91b36f01c0537188d375fce9515abb0df37cc6078d8317ba688a126a6b7ad4f2b31a76

test:
  secret_key_base: 86cefed233a2af460d81e124c71d34978dfef643d399d963d21791ca27393b3ef79949ecbb15bce4b63ea1ae6278fcadbef87ab945497ce1c6d25809b1d1a4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
